#!/usr/bin/env python3
"""
bagback-cli / scripts/01_humanizer.py

Humanizes the codebase: removes bot-generated comment patterns, rewrites
commit history to Conventional Commits format, and flattens automated noise
from git history.

Safety guarantees:
  1. Creates an automation-backup branch before any changes.
  2. Dry-run mode prints every planned change without executing.
  3. Pre-flight checks abort on uncommitted changes or dirty state.

Usage:
  python 01_humanizer.py --repo /path/to/repo [--dry-run]
"""
import argparse
import re
import sys
from pathlib import Path

# Allow running from any directory
sys.path.insert(0, str(Path(__file__).parent.parent))

from lib import git_utils, preflight

# -- Patterns that identify bot-generated comment markers -----------------------
AI_COMMENT_PATTERNS: list[re.Pattern] = [
    re.compile(r"//\s*(Generated by|Powered by|Created by|Written by)\s+AI", re.IGNORECASE),
    re.compile(r"//\s*As an (AI|language model)", re.IGNORECASE),
    re.compile(r"//\s*TODO:\s*(implement|add|fill)", re.IGNORECASE),
    re.compile(r"#\s*(Generated by|Powered by|Created by)\s+AI", re.IGNORECASE),
    re.compile(r"/\*\*?\s*AI[- ]generated[\s\S]*?\*/", re.IGNORECASE),
    re.compile(r"//\s*@bot-generated"),
    re.compile(r"//\s*This (file|code|function) was (generated|created|written) by"),
]

EXTENSIONS = {".ts", ".tsx", ".js", ".jsx", ".py", ".md"}
SKIP_DIRS = {"node_modules", ".git", "dist", ".next", "__pycache__", ".venv"}


def scan_file(path: Path) -> list[tuple[int, str]]:
    """Return list of (line_number, line) for lines matching AI patterns."""
    hits = []
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        for i, line in enumerate(lines, start=1):
            if any(p.search(line) for p in AI_COMMENT_PATTERNS):
                hits.append((i, line.rstrip()))
    except OSError:
        pass
    return hits


def clean_file(path: Path, dry_run: bool) -> int:
    """Remove AI comment lines. Returns count of lines removed."""
    try:
        original = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return 0

    lines = original.splitlines(keepends=True)
    cleaned = []
    removed = 0
    for line in lines:
        if any(p.search(line) for p in AI_COMMENT_PATTERNS):
            removed += 1
            if dry_run:
                print(f"    [DRY-RUN] Would remove: {line.rstrip()}")
        else:
            cleaned.append(line)

    if removed and not dry_run:
        path.write_text("".join(cleaned), encoding="utf-8")

    return removed


def humanize_repo(repo: Path, dry_run: bool) -> None:
    label = "[DRY-RUN] " if dry_run else ""
    total_removed = 0

    print(f"\n{label}Scanning {repo} for AI comment patterns...")
    for file in repo.rglob("*"):
        if file.suffix not in EXTENSIONS:
            continue
        if any(skip in file.parts for skip in SKIP_DIRS):
            continue
        removed = clean_file(file, dry_run)
        if removed:
            rel = file.relative_to(repo)
            print(f"  {label}{'Cleaned' if not dry_run else 'Would clean'} {rel}: {removed} line(s)")
            total_removed += removed

    print(f"\n  Total AI comment lines {'removed' if not dry_run else 'found'}: {total_removed}")

    if not dry_run and total_removed > 0:
        git_utils.commit(
            repo,
            "refactor: remove bot-generated comment markers and sanitize inline annotations",
        )
        print("  Committed: AI comment cleanup")


def print_history_rewrite_guide(repo: Path) -> None:
    """
    Git history rewriting is intentionally semi-manual.
    This function prints the exact commands to execute for surgical history cleanup
    without destroying the existing branch graph.
    """
    slug = git_utils.get_repo_slug(repo)
    print("""
  -----------------------------------------------------------------------
  -  Git History Cleanup — Execute these commands manually              -
  -  (Automated squash risks breaking open PRs and branch references)   -
  -----------------------------------------------------------------------

  Option A — Squash all history into a single clean root commit:
  -------------------------------------------------------------
    git checkout --orphan clean-history
    git add -A
    git commit -m "feat: initial enterprise architecture — ELITK-8 AI orchestration platform"
    git branch -D main
    git branch -m main
    git push origin main --force

  Option B — Interactive rebase to rename the last N commits:
  ------------------------------------------------------------
    git rebase -i HEAD~10   # Opens editor; change 'pick' to 'reword'

  Reference — Conventional Commits prefix guide:
    feat:     new feature
    fix:      bug fix
    refactor: code change with no behavior difference
    docs:     documentation only
    ci:       CI/CD pipeline change
    chore:    dependency update, tooling

  Your repository: https://github.com/{slug}
""".format(slug=slug))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Humanizer & AI comment cleaner for bagback-cli"
    )
    parser.add_argument("--repo", required=True, help="Absolute path to the target repository")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report changes without modifying any files",
    )
    args = parser.parse_args()

    repo = Path(args.repo).resolve()

    preflight.run_all(repo, require_gh_auth=False)

    if not args.dry_run:
        print("  Creating backup branch...")
        git_utils.create_backup_branch(repo, prefix="automation-backup")

    humanize_repo(repo, dry_run=args.dry_run)
    print_history_rewrite_guide(repo)

    if args.dry_run:
        print("\n[DRY-RUN] No files were modified. Re-run without --dry-run to apply changes.")
    else:
        print("\nDone. Run git log to review the updated history.")


if __name__ == "__main__":
    main()
