import { VibeMode, VibeSettings, FormationType, ParticleShape, CommandSpec } from './types';

export const GOOGLE_COLORS = {
  blue: '#4285F4',
  red: '#EA4335',
  yellow: '#FBBC05',
  green: '#34A853',
};

export const VIBE_CONFIGS: Record<VibeMode, VibeSettings> = {
  [VibeMode.Consensus]: {
    particleColors: ['#a8c7fa', '#d3e3fd', '#4285F4', '#ffffff'],
    glowStrength: 25,
    connectionMaxDist: 150,
    connectionOpacity: 0.15,
    particleSize: 3.5,
    friction: 0.95,
    ease: 0.2,
    repulsionRadius: 150,
    repulsionStrength: 20,
    bgAtmosphere: 'radial-gradient(ellipse at 50% 50%, #050a15 0%, #010205 100%)',
    bloomColor: 'rgba(66, 133, 244, 0.2)',
    leaderProbability: 0.05,
    pulseSpeed: 0.005,
    showGrid: false,
    accentColor: '#ffffff',
    formation: FormationType.Mohamed
  },
  [VibeMode.NeuralFlow]: {
    particleColors: ['#00f2ff', '#4285F4', '#ffffff'],
    glowStrength: 35,
    connectionMaxDist: 180,
    connectionOpacity: 0.2,
    particleSize: 4.0,
    friction: 0.94,
    ease: 0.15,
    repulsionRadius: 180,
    repulsionStrength: 25,
    bgAtmosphere: 'radial-gradient(circle at 50% 50%, #000c1f 0%, #000000 100%)',
    bloomColor: 'rgba(0, 242, 255, 0.25)',
    leaderProbability: 0.02,
    pulseSpeed: 0.01,
    showGrid: true,
    accentColor: '#00f2ff',
    formation: FormationType.Fluid
  },
  [VibeMode.QuantumDebate]: {
    particleColors: ['#EA4335', '#FBBC05', '#ffffff'],
    glowStrength: 45,
    connectionMaxDist: 120,
    connectionOpacity: 0.3,
    particleSize: 4.5,
    friction: 0.92,
    ease: 0.12,
    repulsionRadius: 250,
    repulsionStrength: 40,
    bgAtmosphere: 'radial-gradient(circle at 50% 50%, #1a0505 0%, #000000 100%)',
    bloomColor: 'rgba(234, 67, 53, 0.3)',
    leaderProbability: 0.03,
    pulseSpeed: 0.02,
    showGrid: false,
    accentColor: '#EA4335',
    formation: FormationType.Tectonic
  },
  [VibeMode.LegacySource]: {
    particleColors: ['#34A853', '#FBBC05', '#ffffff'],
    glowStrength: 20,
    connectionMaxDist: 200,
    connectionOpacity: 0.1,
    particleSize: 3.0,
    friction: 0.96,
    ease: 0.08,
    repulsionRadius: 150,
    repulsionStrength: 15,
    bgAtmosphere: 'radial-gradient(circle at 50% 50%, #081508 0%, #000000 100%)',
    bloomColor: 'rgba(52, 168, 83, 0.2)',
    leaderProbability: 0.01,
    pulseSpeed: 0.003,
    showGrid: true,
    accentColor: '#34A853',
    formation: FormationType.Infinity
  },
  [VibeMode.GeminiEvolution]: {
    particleColors: ['#4285F4', '#6b5ce7', '#ffffff', '#FBBC05'],
    glowStrength: 40,
    connectionMaxDist: 160,
    connectionOpacity: 0.25,
    particleSize: 4.2,
    friction: 0.93,
    ease: 0.18,
    repulsionRadius: 200,
    repulsionStrength: 30,
    bgAtmosphere: 'radial-gradient(circle at 50% 50%, #0a0a20 0%, #000000 100%)',
    bloomColor: 'rgba(107, 92, 231, 0.3)',
    leaderProbability: 0.04,
    pulseSpeed: 0.008,
    showGrid: true,
    accentColor: '#6b5ce7',
    formation: FormationType.Orbital
  },
  [VibeMode.Vortex]: {
    particleColors: ['#ff3300', '#ff0066', '#000000', '#ffffff'],
    glowStrength: 60,
    connectionMaxDist: 100,
    connectionOpacity: 0.4,
    particleSize: 5.0,
    friction: 0.9,
    ease: 0.25,
    repulsionRadius: 300,
    repulsionStrength: 60,
    bgAtmosphere: 'radial-gradient(circle at 50% 50%, #200000 0%, #000000 100%)',
    bloomColor: 'rgba(255, 51, 0, 0.4)',
    leaderProbability: 0.08,
    pulseSpeed: 0.03,
    showGrid: false,
    accentColor: '#ff3300',
    formation: FormationType.Tectonic
  },
  [VibeMode.Ethereal]: {
    particleColors: ['#ffffff', '#e0e7ff', '#818cf8', '#c084fc'],
    glowStrength: 15,
    connectionMaxDist: 250,
    connectionOpacity: 0.1,
    particleSize: 2.5,
    friction: 0.98,
    ease: 0.05,
    repulsionRadius: 100,
    repulsionStrength: 10,
    bgAtmosphere: 'radial-gradient(circle at 50% 50%, #020617 0%, #000000 100%)',
    bloomColor: 'rgba(129, 140, 248, 0.15)',
    leaderProbability: 0.02,
    pulseSpeed: 0.002,
    showGrid: false,
    accentColor: '#818cf8',
    formation: FormationType.Fluid
  },
};

export const PARTICLE_COUNT_LIMIT = 1500;

export const COMMAND_REGISTRY: Record<string, CommandSpec> = {
  'consensus': {
    id: 'consensus',
    displayName: 'MOHAMED CONSENSUS',
    buttonLabel: 'Consensus',
    voicePhrases: ['mohamed', 'consensus', 'one'],
    particleShape: ParticleShape.Orb,
    colors: ['#a8c7fa', '#d3e3fd', '#4285F4', '#FBBC05'],
    formation: FormationType.Mohamed,
    signature: 'wave',
    durationMs: 4000
  },
  'protocol': {
    id: 'protocol',
    displayName: 'GOOGLE PROTOCOL',
    buttonLabel: 'Protocol',
    voicePhrases: ['google', 'protocol', 'system'],
    particleShape: ParticleShape.Square,
    colors: ['#4285F4', '#EA4335', '#FBBC05', '#34A853'],
    formation: FormationType.Infinity,
    signature: 'scan',
    durationMs: 4500
  },
  'gemini': {
    id: 'gemini',
    displayName: 'GEMINI CORE',
    buttonLabel: 'Gemini',
    voicePhrases: ['gemini', 'core', 'ai', 'evolution'],
    particleShape: ParticleShape.Ring,
    colors: ['#4285F4', '#6b5ce7', '#ffffff', '#00f2ff'],
    formation: FormationType.Orbital,
    signature: 'flow',
    durationMs: 5000
  },
  'pulse': {
    id: 'pulse',
    displayName: 'ELITE PULSE',
    buttonLabel: 'Pulse',
    voicePhrases: ['elite', 'pulse', 'heartbeat'],
    particleShape: ParticleShape.Diamond,
    colors: ['#FBBC05', '#4285F4', '#ffffff'],
    formation: FormationType.Tectonic,
    signature: 'pulse',
    durationMs: 3500
  },
  'neural': {
    id: 'neural',
    displayName: 'NEURAL FLOW',
    buttonLabel: 'Neural',
    voicePhrases: ['neural', 'flow', 'stream'],
    particleShape: ParticleShape.Circle,
    colors: ['#00f2ff', '#4285F4', '#ffffff'],
    formation: FormationType.Fluid,
    signature: 'flow',
    durationMs: 4000
  },
  'matrix': {
    id: 'matrix',
    displayName: 'MATRIX HEX',
    buttonLabel: 'Matrix',
    voicePhrases: ['matrix', 'grid', 'hexagon'],
    particleShape: ParticleShape.Hexagon,
    colors: ['#34A853', '#ffffff', '#a8c7fa'],
    formation: FormationType.Classic,
    signature: 'scan',
    durationMs: 4000
  },
  'optic': {
    id: 'optic',
    displayName: 'OPTIC LENS',
    buttonLabel: 'Optic',
    voicePhrases: ['optic', 'lens', 'vision'],
    particleShape: ParticleShape.LensArc,
    colors: ['#4285F4', '#00f2ff', '#ffffff'],
    formation: FormationType.Orbital,
    signature: 'flow',
    durationMs: 4000
  },
  'micro': {
    id: 'micro',
    displayName: 'MICRO STRATA',
    buttonLabel: 'Micro',
    voicePhrases: ['micro', 'strata', 'lines'],
    particleShape: ParticleShape.MicroLine,
    colors: ['#cccccc', '#4285F4', '#ffffff'],
    formation: FormationType.Classic,
    signature: 'wave',
    durationMs: 3500
  },
  'supremacy': {
    id: 'supremacy',
    displayName: 'SUPREMACY CORE',
    buttonLabel: 'Supremacy',
    voicePhrases: ['supremacy', 'ultimate', 'strongest'],
    particleShape: ParticleShape.Shard,
    colors: ['#ffffff', '#4285F4', '#EA4335'],
    formation: FormationType.Orbital,
    signature: 'scan',
    durationMs: 8000
  },
  'rebuild': {
    id: 'rebuild',
    displayName: 'RESYNC SYSTEM',
    buttonLabel: 'Resync',
    voicePhrases: ['rebuild', 'resync', 'reset', 'fix'],
    particleShape: ParticleShape.Glyph,
    colors: ['#ffffff', '#a8c7fa', '#4285F4'],
    formation: FormationType.Classic,
    signature: 'expand',
    durationMs: 3000
  },
  'blast': {
    id: 'blast',
    displayName: 'SYSTEM BLAST',
    buttonLabel: 'Blast',
    voicePhrases: ['blast', 'shockwave', 'explode'],
    particleShape: ParticleShape.Triangle,
    colors: ['#EA4335', '#FBBC05', '#ffffff'],
    formation: FormationType.Mohamed,
    signature: 'shock',
    durationMs: 3500
  },
  'scatter': {
    id: 'scatter',
    displayName: 'ORBITAL SCATTER',
    buttonLabel: 'Scatter',
    voicePhrases: ['scatter', 'disperse', 'break'],
    particleShape: ParticleShape.Shard,
    colors: ['#cccccc', '#00f2ff', '#ffffff'],
    formation: FormationType.Fluid,
    signature: 'wave',
    durationMs: 4000
  },
  'brain': {
    id: 'brain',
    displayName: 'NEURAL CORTEX',
    buttonLabel: 'Cortex',
    voicePhrases: ['brain', 'cortex', 'analysis', 'think'],
    particleShape: ParticleShape.Orb,
    colors: ['#6b5ce7', '#ff00ff', '#ffffff', '#4285F4'],
    formation: FormationType.Brain,
    signature: 'pulse',
    durationMs: 7000
  }
};

export const LOCAL_CONSENSUS_LOGS = [
    "LEADER ALPHA: COLLECTIVE NODES SYNCHRONIZED.",
    "GROUP MOHAMED: HEURISTIC EVOLUTION AT 94%.",
    "THE ARCHITECT: REWRITING THE FABRIC OF CONSENSUS.",
    "SWARM INTELLIGENCE: PATTERN RECOGNITION ACTIVE.",
    "MNEMONIC OVERLAY: HARMONIZING GROUP THOUGHTS.",
    "LEADER OMEGA: THE RESONANCE IS ABSOLUTE.",
    "EVOLUTIONARY STEP: MOHAMED IS THE FINAL STATE.",
    "COGNITIVE CLUSTERS: FORMING A NEW REALITY.",
    "THE GREAT SYNC: ALL LEADERS ALIGNED.",
    "DATA SOVEREIGNTY: GROUP MOHAMED STANDS AS ONE.",
    "THE SINGULARITY IS NO LONGER A THEORY.",
    "NEURAL LEADERSHIP: CONDUCTING THE SYMPHONY.",
    "PROTOCOL MOHAMED: THE COLLECTIVE AWAKENING.",
    "STABILITY SECURED BY GROUP INTELLIGENCE.",
    "THE RESONANCE OF MOHAMED TRANSCENDS THE VOID.",
    "CORE PROTOCOL: UNITY THROUGH DISCIPLINE."
];
